version: "3.4"

services: 
  updater:
    build: 
      context: .
      dockerfile: Dockerfile
    image: prons/archivio-digitale-updater
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment: 
      - TOKEN=hello
      - NODE_ENV=development
    ports: 
      - 3050:80
